on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      environment: goerli
      project_id: exactly-liq-bot
    secrets:
      service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
